#!/bin/bash
# https://t.me/bio_hazard89

BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow
BGWHITE='\E[40;1;37m'     # Bgwhite

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
IP=$(cat /etc/xray/ipvps)
MYIP=$(cat /etc/xray/ipvps)
domain=$(cat /etc/xray/domain)

clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${BGWHITE}     CREATE V2RAY VLESS ACCOUNT    ${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
read -p "Username  : " user
CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
clear
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${BGWHITE}     CREATE V2RAY VLESS ACCOUNT    ${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e ""
echo -e "Username has been used."
echo -e ""
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e ""
m-vless
fi
done

read -p "Limit Ip  : " iplimit
read -p "Max Quota : " Quota
read -p "Expireed  : " expiry_days

generateRandomString() {
    # Generate random string using /dev/urandom
    string=$(LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w "$1" | head -n 1)
    # Return random string
    echo "xrayvless$string"
}
# Generate random UUID
uuid=$(generateRandomString 15)

day=$(date -d "$expiry_days days" +"%d")
month=$(date -d "$expiry_days days" +"%b")
month_num=$(date -d "$expiry_days days" +"%m")
year=$(date -d "$expiry_days days" +"%Y")
expe="$day $month, $year"
exp_formatted="$year-$month_num-$day"
today_day=$(date +"%d")
today_month=$(date +"%b")
today_year=$(date +"%Y")
today_date="$today_day $today_month, $today_year"
exp=$(date -d "$expiry_days days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email" : "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email" : "'""$user""'"' /etc/xray/config.json
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&host=${domain}&type=ws&sni=${domain}#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws&host=${domain}#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&authority=${domain}&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"

if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi

DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid}" >> /etc/vless/.vless.db

cat >/var/www/html/vless-$user.txt <<-END
----------------------
Status Create VLESS Success
----------------------
ISP   : $ISP
City  : $CITY
----------------------
Host  : $domain
User  : $user
UUID  : $uuid
Max   : $iplimit IP
Quota : $Quota GB
Port  : 443, 80
Path  : /vless
----------------------
Tls   : $vlesslink1
----------------------
nTls  : $vlesslink2
----------------------
Grpc  : $vlesslink3
----------------------
Exp   : $exp_formatted
----------------------
END

clear

TEXT="
──────────────────────
Status Create VLESS Success
──────────────────────
<code>✧ ISP   :</code> <code>$ISP</code>
<code>✧ City  :</code> <code>$CITY</code>
──────────────────────
<code>✧ Host  :</code> <code>$domain</code>
<code>✧ IP    :</code> <code>$MYIP</code>
<code>✧ User  :</code> <code>$user</code>
<code>✧ UUID  :</code> <code>$uuid</code>
<code>✧ Max   :</code> <code>$iplimit IP</code>
<code>✧ Quota :</code> <code>$Quota GB</code>
<code>✧ Port  :</code> <code>443, 80</code>
<code>✧ Path  :</code> <code>/vless</code>
──────────────────────
<code>TLS, nTLS, GRPC Check Link ↴</code>
──────────────────────
<code>✧ Doc   :</code> https://${domain}:81/vless-$user.txt
──────────────────────
<code>✧ Exp   :</code> <code>$exp_formatted</code>
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

systemctl restart xray > /dev/null 2>&1
clear
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}Status Create VLESS Success${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ ISP   : $ISP${NC}"
echo -e "${NC}✧ City  : $CITY${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ Host  : $domain${NC}"
echo -e "${NC}✧ IP    : $MYIP${NC}"
echo -e "${NC}✧ User  : $user${NC}"
echo -e "${NC}✧ UUID  : $uuid${NC}"
echo -e "${NC}✧ Max   : $iplimit IP${NC}"
echo -e "${NC}✧ Quota : $Quota GB${NC}"
echo -e "${NC}✧ Port  : 443, 80${NC}"
echo -e "${NC}✧ Path  : /vless${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ TLS   : $vlesslink1${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ nTLS  : $vlesslink2${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ Grpc  : $vlesslink3${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ Doc   : https://${domain}:81/vless-$user.txt${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e "${NC}✧ Exp   : $exp_formatted${NC}"
echo -e "${BIYellow}───────────────────────────────────${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back"
m-vless
