#!/bin/bash
# https://t.me/bio_hazard89

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'
UPDATE="https://abc.xcodehoster.com/"
BOT="https://abc.xcodehoster.com/"

clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m   MENU SETTING NOTIFIKASI TELEGRAM BOT   \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
echo -e "  [\033[1;96m01\E[0m] Add Bot Notifikasi${NC}"
echo -e "  [\033[1;96m02\E[0m] Delete Bot Notifikasi${NC}"
echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -p "Select From Options ➤ " menu

case $menu in
1) clear ;
    add-bot-notif
    ;;
2) clear ;
    del-bot-notif
    ;;
0) clear ; menu ; exit ;;
x) exit ;;
*) echo "Pilihan anda tidak tersedia! " ; sleep 1 ; bot ;;
esac
