#!/bin/bash
# https://t.me/bio_hazard89

MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
YELL='\033[0;33m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
BGWHITE='\e[0;100;37m'

clear 
echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       MENU MONITOR BANDWITH SERVER       \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "  [01] View Total Remaining Bandwidth"
echo -e "  [02] Usage Table Every 5 Minutes"
echo -e "  [03] Usage Table Every Hour"
echo -e "  [04] Usage Table Every Day"
echo -e "  [05] Usage Table Every Month"
echo -e "  [06] Usage Table Every Year"
echo -e "  [07] Highest Usage Table"
echo -e "  [08] Hourly Usage Statistics"
echo -e "  [09] View Current Active Usage"
echo -e "  [10] View Current Active Traffic Usage [5s]"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -p "Select From Options ➤ " opt

case $opt in
1)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m      TOTAL REMAINING SERVER BANDWIDTH    \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

2)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m      TOTAL BANDWIDTH EVERY 5 MINUTES     \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -5

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

3)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m        TOTAL BANDWIDTH EVERY HOUR        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -h

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

4)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m        TOTAL BANDWIDTH EVERY DAY         \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -d

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

5)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       TOTAL BANDWIDTH EVERY MONTH        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -m

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

6)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       TOTAL BANDWIDTH EVERY YEAR         \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -y

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

7)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m         HIGHEST BANDWIDTH USAGE          \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -t

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

8)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       HOURLY USAGE STATISTICS            \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -hg

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

9)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m          LIVE BANDWIDTH CURRENT          \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "Press [ Ctrl+C ] » To-Exit"
echo -e ""

vnstat -l

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

10)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m     LIVE BANDWIDTH USAGE TRAFFIC         \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -tr

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

0) clear ; menu ; exit ;;
x) exit ;;
*) echo "Your choice is not available! " ; sleep 1 ; bw ;;
esac
