#!/bin/bash
# https://t.me/bio_hazard89

MYIP=$(wget -qO- ipinfo.io/ip);
echo "Checking VPS"
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
YELL='\033[0;33m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
BGWHITE='\e[0;100;37m'

clear 
echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       MENU MONITOR BANDWITH SERVER       \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "  [01] Lihat Total Bandwith Tersisa"
echo -e "  [02] Tabel Penggunaan Setiap 5 Menit"
echo -e "  [03] Tabel Penggunaan Setiap Jam"
echo -e "  [04] Tabel Penggunaan Setiap Hari"
echo -e "  [05] Tabel Penggunaan Setiap Bulan"
echo -e "  [06] Tabel Penggunaan Setiap Tahun"
echo -e "  [07] Tabel Penggunaan Tertinggi"
echo -e "  [08] Statistik Penggunaan Setiap Jam"
echo -e "  [09] Lihat Penggunaan Aktif Saat Ini"
echo -e "  [10] Lihat Trafik Penggunaan Aktif Saat Ini [5s]"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -p "Select From Options ➤ " opt

case $opt in
1)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m      TOTAL BANDWITH SERVER TERSISA       \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

2)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m      TOTAL BANDWITH SETIAP 5 MENIT       \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -5

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

3)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m        TOTAL BANDWITH SETIAP JAM         \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -h

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

4)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m        TOTAL BANDWITH SETIAP HARI        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -d

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

5)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       TOTAL BANDWITH SETIAP BULAN        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -m

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

6)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       TOTAL BANDWITH SETIAP TAHUN        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -y

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

7)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m         TOTAL BANDWITH TERTINGGI         \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -t

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

8)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       STATISTIK TERPAKAI SETIAP JAM      \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -hg

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

9)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m          LIVE BANDWITH SAAT INI          \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "Press [ Ctrl+C ] » To-Exit"
echo -e ""

vnstat -l

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

10)
clear 
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m     LIVE TRAFIK PENGGUNAAN BANDWITH      \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""

vnstat -tr

echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
bw
;;

0) clear ; menu ; exit ;;
x) exit ;;
*) echo "Pilihan anda tidak tersedia! " ; sleep 1 ; bw ;;
esac
