#!/bin/bash
# https://t.me/bio_hazard89

clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m           RENAME LICENSE HOME            \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
read -p "Input Username : " user
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
clear
rm /etc/license
touch /etc/license
echo "$user" >>/etc/license
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m        RENAME LICENSE HOME SUCCESS       \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
echo -e "\e[33mUsername Info   : $user"
echo -e "\e[33mLicense Utama   : GEMILANG KINASIH STORE"
echo -e "\e[33mProcess Rename  : Success"
echo -e ""
echo -e "\e[33m──────────────────────────────────────────\033[0m"
read -n 1 -s -r -p "Press any key to back"
menu