#!/bin/bash
# https://t.me/bio_hazard89

BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow
BGWHITE='\E[40;1;37m'     # Bgwhite

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/flowingwaters26/install/main/sogokregister"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    clear
    echo -e "${BIYellow}────────────────────────────────────────────${NC}"
    echo -e "${BGWHITE}          404 NOT FOUND AUTOSCRIPT          ${NC}"
    echo -e "${BIYellow}────────────────────────────────────────────${NC}"
    echo -e ""
    echo -e "${BIYellow}           ${RED}! PERMISSION DENIED !${NC}"
    echo -e "${BIYellow}  Your VPS${NC} $ipsaya ${BIYellow}has been banned${NC}"
    echo -e "${BIYellow}     Buy access permissions for scripts${NC}"
    echo -e "${BIYellow}       Wa admin : wa.me/+254797264947${NC}"
    echo -e "${BIYellow}     Tele admin : t.me/bio_hazard89${NC}"
    echo -e "${BIYellow}────────────────────────────────────────────${NC}"
    exit 0
  fi
}
checking_sc
clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m         MENU SETTING TELEGRAM BOT        \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "${NC} [01] Menu BOT Panel${NC}"
echo -e "${NC} [02] Menu BOT Notifikasi${NC}"
echo -e "${NC} [03] Menu BOT Backup${NC}"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -p "Select From Options ➤ " menu

case $menu in
1 | 01) clear ; checking_sc ; mbot-panel ;;
2 | 02) clear ; checking_sc ; bot ;;
3 | 03) clear ; checking_sc ; 
    echo -e "Notification ! : "
    echo -e "Sebelum Menggunakan BOT Backup"
    echo -e "Harap Setup Dulu ID & Bot Token Kamu !"
    sleep 3
    mbot-backup ;;
0) clear ; menu ; exit ;;
x) exit ;;
*) echo "Pilihan anda tidak tersedia! " ; sleep 1 ; m-bot ;;
esac