#!/bin/bash
# https://t.me/bio_hazard89

BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
UWhite='\033[4;37m'       # White
BIYellow='\033[1;93m'     # Yellow
BGWHITE='\E[40;1;37m'     # Bgwhite

RED="\033[31m"
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
YELL='\033[0;33m'

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/flowingwaters26/install/main/sogokregister"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    clear
    echo -e "${BIYellow}────────────────────────────────────────────${NC}"
    echo -e "${BGWHITE}          404 NOT FOUND AUTOSCRIPT          ${NC}"
    echo -e "${BIYellow}────────────────────────────────────────────${NC}"
    echo -e ""
    echo -e "${BIYellow}           ${RED}! PERMISSION DENIED !${NC}"
    echo -e "${BIYellow}  Your VPS${NC} $ipsaya ${BIYellow}has been banned${NC}"
    echo -e "${BIYellow}     Buy access permissions for scripts${NC}"
    echo -e "${BIYellow}       Wa admin : wa.me/+254797264947${NC}"
    echo -e "${BIYellow}     Tele admin : t.me/bio_hazard89${NC}"
    echo -e "${BIYellow}────────────────────────────────────────────${NC}"
    exit 0
  fi
}
checking_sc
clear
echo -e "${BICyan} ┌──────────────────────────────────────────────┐${NC}"
echo -e "${BIWhite}     ${UWhite}MENU EXSTRA SETTING ${NC}"
echo -e ""
echo -e "${BICyan}     [${BIWhite}01${BICyan}] CHANGE BENNER${NC}"
echo -e "${BICyan}     [${BIWhite}02${BICyan}] RESTART SERVICE${NC}"
echo -e "${BICyan}     [${BIWhite}03${BICyan}] CHECK INFO PORT${NC}"
echo -e "${BICyan}     [${BIWhite}04${BICyan}] FIX CERT DOMAIN${NC}"
echo -e "${BICyan}     [${BIWhite}05${BICyan}] RECOVERY XRAY${NC}"
echo -e "${BICyan}     [${BIWhite}06${BICyan}] LIMIT SERVICE${NC}"
echo -e "${BICyan}     [${BIWhite}07${BICyan}] DELETE ALL EXP${NC}"
echo -e "${BICyan} └─────────────────────────────────────────────┘${NC}"
echo -e "${BIYellow}     Press x or [ Ctrl+C ] • To-${BIWhite}Exit${NC}"
echo -e ""
read -p " Select From Options ➤ " menu

case $menu in
1)  clear ;
    nano /etc/kyt.txt
    ;;
2)  clear ;
    restart
    ;;
3)  clear ;
    port
    ;;
4)  clear ;
    fixcert
    ;;
5)  clear ;
    recoveryxray
    ;;
6)  clear ;
    limitservice ;
    ;;
7)  clear ;
    xp ;
    ;;
0) clear ; menu ; exit ;;
x) exit ;;
*) echo " Pilihan anda tidak tersedia! " ; sleep 1 ; m-system ;;
esac