#!/bin/bash
# https://t.me/bio_hazard89

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'

restart-bot(){
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    systemctl restart xbot
}
netfilter-persistent
clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m    RESTART PANEL TELEGRAM BOT SUCCESS    \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
echo -e "\033[1;91mRestart Bot Service\033[1;37m"
fun_bar 'res1'
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press [ Enter ] To Back On Menu"
mbot-panel
}

stop-bot(){
clear
fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[0;32m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[0;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "\033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
    done
    echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
res1() {
    systemctl stop xbot
}
netfilter-persistent
clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m       STOP PANEL TELEGRAM BOT SUCCESS    \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
echo -e "\033[1;91mStop Bot Service\033[1;37m"
fun_bar 'res1'
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -n 1 -s -r -p "Press [ Enter ] To Back On Menu"
mbot-panel
}

#satusbot
mybot=$(systemctl status xbot | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
# STATUS SERVICE  BOT 
if [[ $mybot == "running" ]]; then 
   status_bot="${GREEN}ON\033[0m"
else
   status_bot="${RED}OFF\033[0m"
fi
#####
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
grenbo="\e[92;1m"
NC='\033[0m'

echo -e "\e[32mloading...\e[0m"
clear
MYIP=$(wget -qO- ipinfo.io/ip);
clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m      MENU SETTING PANEL TELEGRAM BOT     \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "  Status Bot [${status_bot}]"
echo -e ""
echo -e "  [01] Create Bot Telegram${NC}"
echo -e "  [02] Delete Bot Telegram${NC}"
echo -e "  [03] Stop Bot Panel${NC}"
echo -e "  [04] Restart Bot Panel${NC}"
echo -e "  [05] Delete Bot Notif${NC}"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e ""
read -p "Select From Options ➤ " opt

case $opt in
01 | 1) clear ; wget https://raw.githubusercontent.com/masterxone/pusaka/main/autoscript/sogokbot/bot.sh && chmod +x bot.sh && ./bot.sh ;;
02 | 2) clear ; hapus-bot ;;
03 | 3) clear ; stop-bot ;;
04 | 4) clear ; restart-bot ;;
05 | 5) clear ; del-bot-notif ;;
0) clear ; menu ; exit ;;
x) exit ;;
*) echo "Your choice is not available! " ; sleep 1 ; mbot-panel ;;
esac