#!/bin/bash
# https://t.me/bio_hazard89

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
plain='\033[0m'
blue='\033[0;34m'
ungu='\033[0;35m'
Green="\033[32m"
Red="\033[31m"
WhiteB="\e[5;37m"
BlueCyan="\e[5;36m"
Green_background="\033[42;37m"
Red_background="\033[41;37m"
Suffix="\033[0m"
NC='\e[0m'

clear

echo -e "${green}░█▀▄▀█░█▀▀░█▀▀▄░█░▒█░░░█▀▀▄░█▀▀▄░█▀▄░█░▄░█░▒█░▄▀▀▄${NC}"
echo -e "${green}░█░▀░█░█▀▀░█░▒█░█░▒█░░░█▀▀▄░█▄▄█░█░░░█▀▄░█░▒█░█▄▄█${NC}"
echo -e "${green}░▀░░▒▀░▀▀▀░▀░░▀░░▀▀▀░░░▀▀▀▀░▀░░▀░▀▀▀░▀░▀░░▀▀▀░█░░░${NC}"
echo -e "${ungu}──────────────────────────────────────────────────${NC}"
echo -e ""
echo -e "${BlueCyan}                    Menu Backup${NC}"
echo -e "${BlueCyan}               t.me/bio_hazard89${NC}"
echo -e "${ungu}──────────────────────────────────────────────────${NC}"
echo ""
echo -e "${BlueCyan}Pilih Nomor Menu : "
echo ""
echo "1). Backup"
echo "2). Restore"
echo "3). Limit Speed"
echo "4). Autobackup"
echo ""
echo -e "${ungu}──────────────────────────────────────────────────${NC}"
echo -e ""
read -p "Pilih Nomor └╼>>> " bro

# Pemilihan berdasarkan input pengguna
if [ "$bro" == "1" ]; then
    figlet "backup" | lolcat
    backup
elif [ "$bro" == "2" ]; then
    figlet "restore" | lolcat
    restore
elif [ "$bro" == "3" ]; then
    figlet "limitspeed"
    limitspeed
elif [ "$bro" == "4" ]; then
    figlet "autobackup"
    autobackup
elif [ "$bro" == "0" ]; then
    menu
else
    echo -e "${Red}Pilihan tidak valid!${NC}"
    menu-backup
fi
